sudo: required
language: bash

services:
    - docker

script:
    - docker  run  -v `pwd`:`pwd` -w `pwd` -i -t  ubuntu pwd
    - docker run -v `$PWD`:/usr/local/magicicada-client ubuntu:16.04 /usr/local/magicicada-client/do-all
