sudo: required
dist: trusty
language: bash

services:
    - docker

before_install:
    - docker pull ubuntu:16.04

script:
    - docker build -t magicicada-client-test-run .
    - docker run magicicada-client-test-run make test