sudo: required
dist: trusty

language: bash

before_install:
    - sudo apt-get update
    - sudo apt install -t trusty-backports lxd lxd-client --yes
    - sudo lxd init --auto
    - sudo lxc launch ubuntu:trusty travis
    - sudo lxc network create testbr0
    - sudo lxc network attach-profile testbr0 default eth0
    - sudo lxc exec travis -- apt-get update --yes
